In [1]:
!pip install deep-translator
!pip install langdetect
!pip install pandas

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (4.13.5)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.12/dist-packages (from deep-translator) (2.32.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.5.20)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 2.1 MB/s eta 0:00:00
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4
Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 32.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=5450cbf4dfecdc4639afe60e5feb51c0631456f765f789c9b90e2d887abab233
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
from deep_translator import GoogleTranslator
from langdetect import detect
import pandas as pd

In [3]:
text = "Bonjour tout le monde"

language = detect(text)

print("Detected Language:", language)

Detected Language: fr

In [4]:
def translate_text(text, target_language):

    translated = GoogleTranslator(
        source='auto',
        target=target_language
    ).translate(text)

    return translated

In [5]:
sentence = "Artificial Intelligence is changing the world."

translated_text = translate_text(
    sentence,
    "hi"
)

print("Original:")
print(sentence)

print("\nTranslated:")
print(translated_text)

Original:
Artificial Intelligence is changing the world.

Translated:
आर्टिफिशियल इंटेलिजेंस दुनिया को बदल रहा है।

In [6]:
languages = {
    "French": "fr",
    "German": "de",
    "Spanish": "es",
    "Hindi": "hi",
    "Telugu": "te",
    "Tamil": "ta",
    "Japanese": "ja"
}

text = "Machine Learning is fascinating."

for language_name, code in languages.items():

    translated = translate_text(
        text,
        code
    )

    print(f"{language_name}:")
    print(translated)
    print("-" * 50)

French:
L’apprentissage automatique est fascinant.
--------------------------------------------------
German:
Maschinelles Lernen ist faszinierend.
--------------------------------------------------
Spanish:
El aprendizaje automático es fascinante.
--------------------------------------------------
Hindi:
मशीन लर्निंग आकर्षक है.
--------------------------------------------------
Telugu:
మెషిన్ లెర్నింగ్ మనోహరమైనది.
--------------------------------------------------
Tamil:
இயந்திர கற்றல் கவர்ச்சிகரமானது.
--------------------------------------------------
Japanese:
機械学習は魅力的です。
--------------------------------------------------

In [7]:
history = []

sample_text = "Welcome to Artificial Intelligence"

translated = translate_text(
    sample_text,
    "fr"
)

history.append(
    {
        "Original": sample_text,
        "Translated": translated
    }
)

history_df = pd.DataFrame(history)

history_df

,Original,Translated
0,Welcome to Artificial Intelligence,Bienvenue dans l'intelligence artificielle

In [8]:
sample_dataset = [
    {
        "English": "Good Morning",
        "French": "Bonjour"
    },
    {
        "English": "How are you?",
        "French": "Comment allez-vous?"
    },
    {
        "English": "Machine Learning is powerful",
        "French": "L'apprentissage automatique est puissant"
    },
    {
        "English": "Artificial Intelligence is changing the world",
        "French": "L'intelligence artificielle change le monde"
    },
    {
        "English": "Welcome to CodeAlpha Internship",
        "French": "Bienvenue au stage CodeAlpha"
    }
]

dataset_df = pd.DataFrame(sample_dataset)

dataset_df

,English,French
0,Good Morning,Bonjour
1,How are you?,Comment allez-vous?
2,Machine Learning is powerful,L'apprentissage automatique est puissant
3,Artificial Intelligence is changing the world,L'intelligence artificielle change le monde
4,Welcome to CodeAlpha Internship,Bienvenue au stage CodeAlpha

In [9]:
correct = 0

for index, row in dataset_df.iterrows():

    translated = translate_text(
        row["English"],
        "fr"
    )

    print("Original :", row["English"])
    print("Expected :", row["French"])
    print("Predicted:", translated)
    print("-"*50)

Original : Good Morning
Expected : Bonjour
Predicted: Bonjour
--------------------------------------------------
Original : How are you?
Expected : Comment allez-vous?
Predicted: Comment vas-tu?
--------------------------------------------------
Original : Machine Learning is powerful
Expected : L'apprentissage automatique est puissant
Predicted: L'apprentissage automatique est puissant
--------------------------------------------------
Original : Artificial Intelligence is changing the world
Expected : L'intelligence artificielle change le monde
Predicted: L'intelligence artificielle change le monde
--------------------------------------------------
Original : Welcome to CodeAlpha Internship
Expected : Bienvenue au stage CodeAlpha
Predicted: Bienvenue au stage CodeAlpha
--------------------------------------------------

In [ ]:
app.py